[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/leveranciers"
  to = "/.netlify/functions/leveranciers"
  status = 200

[[redirects]]
  from = "/api/feedback"
  to = "/.netlify/functions/feedback"
  status = 200
